In [1]:
import sys
datadirs = ''
sys.path.insert(1, datadirs)
savepath = datadirs+'save/'
datapath = datadirs+'data/'

In [2]:
import torch
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
print(device)

cuda:0


In [3]:
import visdom
# python -m visdom.server

In [4]:
from pars import PARS

In [5]:
import utils
from utils import *
from setup_net import *
from loss import *

In [7]:
import importlib
importlib.reload(utils)
from utils import *

In [6]:
from sklearn.linear_model import SGDClassifier, LogisticRegression

In [8]:
pars = PARS(device, datapath, savepath)
pars.architecture = 'CONV6'
pars.LR = 0.0001
pars.clf_lr = 0.001
pars.epochs = 100
pars.clf_epochs = 100
pars.nonlinear = 'hardtanh'
pars.repeat = 1
pars.lam = 1
print(pars)

architecture: CONV6
nonlinear: hardtanh
batch_size: 500
headsize: 64
dataset: Cifar100
loss: SimCLR
OPT: Adam
LR: 0.0001
epochs: 100
clf_dataset: Cifar10
clf_loss: CE
clf_opt: Adam
clf_lr: 0.001
clf_epochs: 100
repeat: 1
device: cuda:0
datapath: data/
savepath: save/
loadnet: None
loadclf: None
lam: 1
headnonlinear: None



In [16]:
vis = visdom.Visdom(port=8097, env='find_lr_0_9')
find_lr_ae(pars, lr0=1e-6, lr1=1e-2, n_epochs=100, vis=vis)

Setting up a new session...


Files already downloaded and verified
Files already downloaded and verified

Rep 1
Sequential(
  (layer0): Sequential(
    (conv): Conv2d(3, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (activation): Hardtanh(min_val=-1.0, max_val=1.0)
  )
  (layer1): Sequential(
    (conv): Conv2d(32, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (maxpool): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
  (layer2): Sequential(
    (conv): Conv2d(32, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (activation): Hardtanh(min_val=-1.0, max_val=1.0)
  )
  (layer3): Sequential(
    (conv): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (maxpool): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
  (layer4): Sequential(
    (conv): Conv2d(64, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (maxpool): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
 

In [11]:
pars = PARS(device, datapath, savepath)
pars.architecture = 'CONV6'
pars.LR = 0.0001
pars.clf_lr = 0.001
pars.epochs = 100
pars.clf_epochs = 100
pars.nonlinear = 'hardtanh'
pars.repeat = 1
pars.lam = 0.1
print(pars)

architecture: CONV6
nonlinear: hardtanh
batch_size: 500
headsize: 64
dataset: Cifar100
loss: SimCLR
OPT: Adam
LR: 0.0001
epochs: 100
clf_dataset: Cifar10
clf_loss: CE
clf_opt: Adam
clf_lr: 0.001
clf_epochs: 100
repeat: 1
device: cuda:0
datapath: data/
savepath: save/
loadnet: None
loadclf: None
lam: 0.1
auxnonlinear: None



In [32]:
vis = visdom.Visdom(port=8097, env='find_lr_0_1')
find_lr_ae(pars, lr0=1e-8, lr1=1e-3, n_epochs=100, vis=vis)

Setting up a new session...


Files already downloaded and verified


KeyboardInterrupt: 

In [12]:
pars = PARS(device, datapath, savepath)
pars.architecture = 'CONV6'
pars.LR = 0.0001
pars.clf_lr = 0.001
pars.epochs = 100
pars.clf_epochs = 100
pars.nonlinear = 'hardtanh'
pars.repeat = 1
pars.lam = -1 # multitask
print(pars)

architecture: CONV6
nonlinear: hardtanh
batch_size: 500
headsize: 64
dataset: Cifar100
loss: SimCLR
OPT: Adam
LR: 0.0001
epochs: 100
clf_dataset: Cifar10
clf_loss: CE
clf_opt: Adam
clf_lr: 0.001
clf_epochs: 100
repeat: 1
device: cuda:0
datapath: data/
savepath: save/
loadnet: None
loadclf: None
lam: -1
auxnonlinear: None



In [7]:
vis = visdom.Visdom(port=8097, env='find_lr_mtl')
find_lr_ae(pars, lr0=1e-5, lr1=1, n_epochs=100, vis=vis)

Setting up a new session...


Files already downloaded and verified
Files already downloaded and verified

Rep 1
Sequential(
  (layer0): Sequential(
    (conv): Conv2d(3, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (activation): Hardtanh(min_val=-1.0, max_val=1.0)
  )
  (layer1): Sequential(
    (conv): Conv2d(32, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (maxpool): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
  (layer2): Sequential(
    (conv): Conv2d(32, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (activation): Hardtanh(min_val=-1.0, max_val=1.0)
  )
  (layer3): Sequential(
    (conv): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (maxpool): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
  (layer4): Sequential(
    (conv): Conv2d(64, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (maxpool): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
 

Epoch 29, loss = 79228.5636, time: 8.8657
reconstruction loss = 206778.2391, similarity loss: 37738.9831
Parameter containing:
tensor([0.2302, 0.2207], requires_grad=True)
Epoch 30, loss = 75448.9683, time: 9.0401
reconstruction loss = 204771.8559, similarity loss: 39430.1884
Parameter containing:
tensor([0.2554, 0.2449], requires_grad=True)
Epoch 31, loss = 71035.4880, time: 9.0120
reconstruction loss = 202890.0972, similarity loss: 39271.8126
Parameter containing:
tensor([0.2823, 0.2717], requires_grad=True)
Epoch 32, loss = 66830.3025, time: 8.8228
reconstruction loss = 200508.3633, similarity loss: 40444.7755
Parameter containing:
tensor([0.3115, 0.3014], requires_grad=True)
Epoch 33, loss = 63518.2556, time: 8.7553
reconstruction loss = 206134.4345, similarity loss: 37355.6649
Parameter containing:
tensor([0.3437, 0.3320], requires_grad=True)
Epoch 34, loss = 58617.3557, time: 8.6969
reconstruction loss = 202628.5302, similarity loss: 37430.7472
Parameter containing:
tensor([0.378

Epoch 77, loss = 143.9475, time: 9.5503
reconstruction loss = 205711.4250, similarity loss: 38212.7742
Parameter containing:
tensor([3.4447, 3.3954], requires_grad=True)
Epoch 78, loss = 125.3470, time: 9.0145
reconstruction loss = 210488.4595, similarity loss: 38058.1368
Parameter containing:
tensor([3.5296, 3.4755], requires_grad=True)
Epoch 79, loss = 109.1450, time: 10.0432
reconstruction loss = 211122.6866, similarity loss: 41993.9651
Parameter containing:
tensor([3.6134, 3.5645], requires_grad=True)
Epoch 80, loss = 91.8170, time: 9.0247
reconstruction loss = 209075.1575, similarity loss: 39159.8628
Parameter containing:
tensor([3.6968, 3.6471], requires_grad=True)
Epoch 81, loss = 77.7652, time: 9.0050
reconstruction loss = 202383.8677, similarity loss: 40741.8526
Parameter containing:
tensor([3.7766, 3.7320], requires_grad=True)
Epoch 82, loss = 67.6964, time: 9.1695
reconstruction loss = 204096.1639, similarity loss: 40335.7834
Parameter containing:
tensor([3.8581, 3.8146], re

Experiments:

In [21]:
pars = PARS(device, datapath, savepath)
pars.architecture = 'CONV6'
pars.LR = 5e-4
pars.clf_lr = 5e-4
pars.epochs = 100
pars.clf_epochs = 100
pars.nonlinear = 'hardtanh'
pars.repeat = 1
pars.lam = -1
print(pars)

architecture: CONV6
nonlinear: hardtanh
batch_size: 500
headsize: 64
dataset: Cifar100
loss: SimCLR
OPT: Adam
LR: 0.0005
epochs: 100
clf_dataset: Cifar10
clf_loss: CE
clf_opt: Adam
clf_lr: 0.0005
clf_epochs: 100
repeat: 1
device: cuda:0
datapath: data/
savepath: save/
loadnet: None
loadclf: None
lam: -1
auxnonlinear: None



In [7]:
vis = visdom.Visdom(port=8097,env='mtl')
train_unsupervised_ae(pars, vis=vis)

Setting up a new session...


save/CONV6/AE/
hardtanh_Cifar100_Adam_LR_0.0005_Epochs_300_CLF_Cifar10_Adam_LR_0.0005_Epochs_100_lam_-1
Files already downloaded and verified
Files already downloaded and verified
Files already downloaded and verified
Files already downloaded and verified

Rep 1
Sequential(
  (layer0): Sequential(
    (conv): Conv2d(3, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (activation): Hardtanh(min_val=-1.0, max_val=1.0)
  )
  (layer1): Sequential(
    (conv): Conv2d(32, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (maxpool): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
  (layer2): Sequential(
    (conv): Conv2d(32, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (activation): Hardtanh(min_val=-1.0, max_val=1.0)
  )
  (layer3): Sequential(
    (conv): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (maxpool): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
  (layer4): Se

Epoch 30, loss = -0.2051, time: 10.2764
reconstruction loss = 0.0681, similarity loss: 1.2882
Parameter containing:
tensor([-1.2425,  0.1117], requires_grad=True)
Epoch 31, loss = -0.2316, time: 10.9696
reconstruction loss = 0.0680, similarity loss: 1.2314
Parameter containing:
tensor([-1.2597,  0.1109], requires_grad=True)
Epoch 32, loss = -0.2527, time: 10.5501
reconstruction loss = 0.0673, similarity loss: 1.1974
Parameter containing:
tensor([-1.2751,  0.1063], requires_grad=True)
Epoch 33, loss = -0.2163, time: 10.3970
reconstruction loss = 0.0677, similarity loss: 1.2849
Parameter containing:
tensor([-1.2885,  0.1101], requires_grad=True)
Epoch 34, loss = -0.2171, time: 10.9488
reconstruction loss = 0.0690, similarity loss: 1.2664
Parameter containing:
tensor([-1.2971,  0.1123], requires_grad=True)
Epoch 35, loss = -0.2770, time: 10.5481
reconstruction loss = 0.0690, similarity loss: 1.1194
Parameter containing:
tensor([-1.3062,  0.1002], requires_grad=True)
Epoch 36, loss = -0.20

Epoch 81, loss = -0.2509, time: 11.7470
reconstruction loss = 0.0671, similarity loss: 1.2199
Parameter containing:
tensor([-1.3443,  0.0979], requires_grad=True)
Epoch 82, loss = -0.2418, time: 11.5364
reconstruction loss = 0.0668, similarity loss: 1.2488
Parameter containing:
tensor([-1.3466,  0.1010], requires_grad=True)
Epoch 83, loss = -0.2402, time: 12.4983
reconstruction loss = 0.0678, similarity loss: 1.2335
Parameter containing:
tensor([-1.3473,  0.1011], requires_grad=True)
Epoch 84, loss = -0.2575, time: 12.0416
reconstruction loss = 0.0670, similarity loss: 1.2058
Parameter containing:
tensor([-1.3482,  0.0998], requires_grad=True)
Epoch 85, loss = -0.2736, time: 12.2229
reconstruction loss = 0.0664, similarity loss: 1.1780
Parameter containing:
tensor([-1.3501,  0.0975], requires_grad=True)
Epoch 86, loss = -0.2367, time: 11.9903
reconstruction loss = 0.0689, similarity loss: 1.2235
Parameter containing:
tensor([-1.3476,  0.0975], requires_grad=True)
Epoch 87, loss = -0.22

Epoch 132, loss = -0.2078, time: 17.2203
reconstruction loss = 0.0689, similarity loss: 1.2954
Parameter containing:
tensor([-1.3415,  0.1199], requires_grad=True)
Epoch 133, loss = -0.2518, time: 17.7553
reconstruction loss = 0.0677, similarity loss: 1.2058
Parameter containing:
tensor([-1.3431,  0.1148], requires_grad=True)
Epoch 134, loss = -0.2428, time: 18.0587
reconstruction loss = 0.0679, similarity loss: 1.2263
Parameter containing:
tensor([-1.3427,  0.1099], requires_grad=True)
Epoch 135, loss = -0.2297, time: 18.1474
reconstruction loss = 0.0687, similarity loss: 1.2440
Parameter containing:
tensor([-1.3401,  0.1121], requires_grad=True)
Epoch 136, loss = -0.2283, time: 18.3518
reconstruction loss = 0.0697, similarity loss: 1.2299
Parameter containing:
tensor([-1.3379,  0.1090], requires_grad=True)
Epoch 137, loss = -0.2617, time: 17.4683
reconstruction loss = 0.0665, similarity loss: 1.2041
Parameter containing:
tensor([-1.3446,  0.1037], requires_grad=True)
Epoch 138, loss 

Epoch 182, loss = -0.2334, time: 11.3481
reconstruction loss = 0.0679, similarity loss: 1.2486
Parameter containing:
tensor([-1.3429,  0.0995], requires_grad=True)
Epoch 183, loss = -0.2527, time: 10.8022
reconstruction loss = 0.0654, similarity loss: 1.2469
Parameter containing:
tensor([-1.3498,  0.1025], requires_grad=True)
Epoch 184, loss = -0.2414, time: 12.5463
reconstruction loss = 0.0677, similarity loss: 1.2334
Parameter containing:
tensor([-1.3496,  0.1047], requires_grad=True)
Epoch 185, loss = -0.2299, time: 12.4245
reconstruction loss = 0.0683, similarity loss: 1.2502
Parameter containing:
tensor([-1.3468,  0.1049], requires_grad=True)
Epoch 186, loss = -0.2252, time: 12.4299
reconstruction loss = 0.0664, similarity loss: 1.2978
Parameter containing:
tensor([-1.3492,  0.1112], requires_grad=True)
Epoch 187, loss = -0.2469, time: 12.0044
reconstruction loss = 0.0647, similarity loss: 1.2751
Parameter containing:
tensor([-1.3582,  0.1117], requires_grad=True)
Epoch 188, loss 

Epoch 232, loss = -0.2429, time: 10.6880
reconstruction loss = 0.0691, similarity loss: 1.2040
Parameter containing:
tensor([-1.3405,  0.1000], requires_grad=True)
Epoch 233, loss = -0.2454, time: 11.1300
reconstruction loss = 0.0676, similarity loss: 1.2261
Parameter containing:
tensor([-1.3443,  0.1003], requires_grad=True)
Epoch 234, loss = -0.2299, time: 11.2264
reconstruction loss = 0.0669, similarity loss: 1.2759
Parameter containing:
tensor([-1.3491,  0.1041], requires_grad=True)
Epoch 235, loss = -0.2612, time: 10.2155
reconstruction loss = 0.0653, similarity loss: 1.2282
Parameter containing:
tensor([-1.3540,  0.1039], requires_grad=True)
Epoch 236, loss = -0.2386, time: 11.6223
reconstruction loss = 0.0689, similarity loss: 1.2187
Parameter containing:
tensor([-1.3474,  0.1033], requires_grad=True)
Epoch 237, loss = -0.2320, time: 11.4161
reconstruction loss = 0.0676, similarity loss: 1.2585
Parameter containing:
tensor([-1.3473,  0.1072], requires_grad=True)
Epoch 238, loss 

Epoch 282, loss = -0.2471, time: 11.1461
reconstruction loss = 0.0682, similarity loss: 1.2107
Parameter containing:
tensor([-1.3464,  0.1056], requires_grad=True)
Epoch 283, loss = -0.2205, time: 13.4938
reconstruction loss = 0.0673, similarity loss: 1.2916
Parameter containing:
tensor([-1.3473,  0.1107], requires_grad=True)
Epoch 284, loss = -0.2037, time: 14.7363
reconstruction loss = 0.0683, similarity loss: 1.3157
Parameter containing:
tensor([-1.3453,  0.1175], requires_grad=True)
Epoch 285, loss = -0.2186, time: 14.6114
reconstruction loss = 0.0674, similarity loss: 1.2963
Parameter containing:
tensor([-1.3470,  0.1184], requires_grad=True)
Epoch 286, loss = -0.2012, time: 12.4658
reconstruction loss = 0.0693, similarity loss: 1.3049
Parameter containing:
tensor([-1.3430,  0.1221], requires_grad=True)
Epoch 287, loss = -0.2467, time: 13.2539
reconstruction loss = 0.0659, similarity loss: 1.2525
Parameter containing:
tensor([-1.3483,  0.1209], requires_grad=True)
Epoch 288, loss 

Epoch 71, loss = 1.2037, val.acc = 0.5894
Epoch 72, loss = 1.2012, val.acc = 0.5902
Epoch 73, loss = 1.1988, val.acc = 0.5910
Epoch 74, loss = 1.1964, val.acc = 0.5916
Epoch 75, loss = 1.1941, val.acc = 0.5926
Epoch 76, loss = 1.1917, val.acc = 0.5940
Epoch 77, loss = 1.1894, val.acc = 0.5942
Epoch 78, loss = 1.1872, val.acc = 0.5954
Epoch 79, loss = 1.1849, val.acc = 0.5960
Epoch 80, loss = 1.1827, val.acc = 0.5958
Epoch 81, loss = 1.1805, val.acc = 0.5958
Epoch 82, loss = 1.1784, val.acc = 0.5972
Epoch 83, loss = 1.1762, val.acc = 0.5974
Epoch 84, loss = 1.1741, val.acc = 0.5980
Epoch 85, loss = 1.1720, val.acc = 0.6000
Epoch 86, loss = 1.1700, val.acc = 0.6002
Epoch 87, loss = 1.1679, val.acc = 0.6012
Epoch 88, loss = 1.1659, val.acc = 0.6014
Epoch 89, loss = 1.1639, val.acc = 0.6022
Epoch 90, loss = 1.1619, val.acc = 0.6032
Epoch 91, loss = 1.1600, val.acc = 0.6034
Epoch 92, loss = 1.1580, val.acc = 0.6034
Epoch 93, loss = 1.1561, val.acc = 0.6042
Epoch 94, loss = 1.1542, val.acc =

In [8]:
pars = PARS(device, datapath, savepath)
pars.architecture = 'CONV6'
pars.LR = 5e-4
pars.clf_lr = 5e-4
pars.epochs = 100
pars.clf_epochs = 100
pars.nonlinear = 'hardtanh'
pars.repeat = 1
pars.lam = 1
print(pars)

architecture: CONV6
nonlinear: hardtanh
batch_size: 500
headsize: 64
dataset: Cifar100
loss: SimCLR
OPT: Adam
LR: 0.0005
epochs: 100
clf_dataset: Cifar10
clf_loss: CE
clf_opt: Adam
clf_lr: 0.0005
clf_epochs: 100
repeat: 1
device: cuda:0
datapath: data/
savepath: save/
loadnet: None
loadclf: None
lam: 1
auxnonlinear: None



In [9]:
vis = visdom.Visdom(port=8097,env='lam_1_sklearn')
sklearn_classifier = SGDClassifier(verbose=1, n_jobs=-1)
train_unsupervised_ae(pars,vis=vis, sklearn_classifier=sklearn_classifier)

Setting up a new session...


save/CONV6/AE/
hardtanh_Cifar100_Adam_LR_0.0005_Epochs_100_CLF_Cifar10_Adam_LR_0.0005_Epochs_100_lam_1
Files already downloaded and verified
Files already downloaded and verified
Files already downloaded and verified
Files already downloaded and verified

Rep 1
Sequential(
  (layer0): Sequential(
    (conv): Conv2d(3, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (activation): Hardtanh(min_val=-1.0, max_val=1.0)
  )
  (layer1): Sequential(
    (conv): Conv2d(32, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (maxpool): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
  (layer2): Sequential(
    (conv): Conv2d(32, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (activation): Hardtanh(min_val=-1.0, max_val=1.0)
  )
  (layer3): Sequential(
    (conv): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (maxpool): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
  (layer4): Seq

[Parallel(n_jobs=-1)]: Using backend ThreadingBackend with 16 concurrent workers.


-- Epoch 1-- Epoch 1

-- Epoch 1-- Epoch 1-- Epoch 1
-- Epoch 1-- Epoch 1
-- Epoch 1-- Epoch 1



-- Epoch 1

Norm: 3604.79, NNZs: 8192, Bias: 41.276313, T: 45000, Avg. loss: 56289.392309
Total training time: 1.06 seconds.
-- Epoch 2
Norm: 4330.50, NNZs: 8192, Bias: -41.383601, T: 45000, Avg. loss: 73297.336301
Total training time: 1.13 seconds.
-- Epoch 2
Norm: 5782.57, NNZs: 8192, Bias: -54.220675, T: 45000, Avg. loss: 77312.667331
Total training time: 1.12 seconds.
-- Epoch 2
Norm: 4395.29, NNZs: 8192, Bias: -4.898155, T: 45000, Avg. loss: 57224.094669
Total training time: 1.14 seconds.
-- Epoch 2
Norm: 5650.10, NNZs: 8192, Bias: -36.785647, T: 45000, Avg. loss: 81004.746366
Total training time: 1.14 seconds.
-- Epoch 2
Norm: 6186.17, NNZs: 8192, Bias: -25.325334, T: 45000, Avg. loss: 74037.475335
Total training time: 1.20 seconds.
-- Epoch 2
Norm: 5375.28, NNZs: 8192, Bias: -42.653661, T: 45000, Avg. loss: 79940.291711Norm: 5023.42, NNZs: 8192, Bias: -54.682589, T: 45000, Avg. loss

[Parallel(n_jobs=-1)]: Done  10 out of  10 | elapsed:  4.8min finished


loss = 9.8947, val.acc = 0.4898
Rep: 1, te.acc = 0.4770

All reps test.acc:
[0.477]


In [13]:
pars = PARS(device, datapath, savepath)
pars.architecture = 'CONV6'
pars.LR = 5e-4
pars.clf_lr = 5e-4
pars.epochs = 100
pars.clf_epochs = 100
pars.nonlinear = 'hardtanh'
pars.repeat = 1
pars.lam = 10 # proportion of the reconstruction loss
print(pars)

architecture: CONV6
nonlinear: hardtanh
batch_size: 500
headsize: 64
dataset: Cifar100
loss: SimCLR
OPT: Adam
LR: 0.0005
epochs: 100
clf_dataset: Cifar10
clf_loss: CE
clf_opt: Adam
clf_lr: 0.0005
clf_epochs: 100
repeat: 1
device: cuda:0
datapath: data/
savepath: save/
loadnet: None
loadclf: None
lam: 10
auxnonlinear: None



In [14]:
vis = visdom.Visdom(port=8097,env='lam_10_sklearn')
sklearn_classifier = SGDClassifier(verbose=0, n_jobs=-1)
train_unsupervised_ae(pars,vis=vis, sklearn_classifier=sklearn_classifier)

Setting up a new session...


save/CONV6/AE/
hardtanh_Cifar100_Adam_LR_0.0005_Epochs_100_CLF_Cifar10_Adam_LR_0.0005_Epochs_100_lam_10
Files already downloaded and verified
Files already downloaded and verified
Files already downloaded and verified
Files already downloaded and verified

Rep 1
Sequential(
  (layer0): Sequential(
    (conv): Conv2d(3, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (activation): Hardtanh(min_val=-1.0, max_val=1.0)
  )
  (layer1): Sequential(
    (conv): Conv2d(32, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (maxpool): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
  (layer2): Sequential(
    (conv): Conv2d(32, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (activation): Hardtanh(min_val=-1.0, max_val=1.0)
  )
  (layer3): Sequential(
    (conv): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (maxpool): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
  (layer4): Se

In [8]:
pars = PARS(device, datapath, savepath)
pars.architecture = 'CONV6'
pars.LR = 5e-4
pars.clf_lr = 5e-4
pars.epochs = 100
pars.clf_epochs = 100
pars.nonlinear = 'hardtanh'
pars.repeat = 1
pars.lam = 20
print(pars)

architecture: CONV6
nonlinear: hardtanh
batch_size: 500
headsize: 64
dataset: Cifar100
loss: SimCLR
OPT: Adam
LR: 0.0005
epochs: 100
clf_dataset: Cifar10
clf_loss: CE
clf_opt: Adam
clf_lr: 0.0005
clf_epochs: 100
repeat: 1
device: cuda:0
datapath: data/
savepath: save/
loadnet: None
loadclf: None
lam: 20
clfnonlinear: None
headnonlinear: None



In [9]:
pars.loadnet = torch.load(
    "save/CONV6/AE/net_rep_1_hardtanh_Cifar100_Adam_LR_0.0005_Epochs_100_CLF_Cifar10_Adam_LR_0.0005_Epochs_100_lam_20.pt")


In [16]:
pars.clf_lr = 1e-5
vis = visdom.Visdom(port=8097,env='clf_lr_1e-5')
train_unsupervised_ae(pars, vis=vis)

Setting up a new session...


save/CONV6/AE/
hardtanh_Cifar100_Adam_LR_0.0005_Epochs_100_CLF_Cifar10_Adam_LR_1e-05_Epochs_100_lam_20
Files already downloaded and verified
Files already downloaded and verified
Files already downloaded and verified
Files already downloaded and verified

Rep 1
Sequential(
  (layer0): Sequential(
    (conv): Conv2d(3, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (activation): Hardtanh(min_val=-1.0, max_val=1.0)
  )
  (layer1): Sequential(
    (conv): Conv2d(32, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (maxpool): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
  (layer2): Sequential(
    (conv): Conv2d(32, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (activation): Hardtanh(min_val=-1.0, max_val=1.0)
  )
  (layer3): Sequential(
    (conv): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (maxpool): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
  (layer4): Seq

In [15]:
pars.clf_lr = 5e-5
vis = visdom.Visdom(port=8097,env='clf_lr_5e-5')
train_unsupervised_ae(pars, vis=vis)

Setting up a new session...


save/CONV6/AE/
hardtanh_Cifar100_Adam_LR_0.0005_Epochs_100_CLF_Cifar10_Adam_LR_5e-05_Epochs_100_lam_20
Files already downloaded and verified
Files already downloaded and verified
Files already downloaded and verified
Files already downloaded and verified

Rep 1
Sequential(
  (layer0): Sequential(
    (conv): Conv2d(3, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (activation): Hardtanh(min_val=-1.0, max_val=1.0)
  )
  (layer1): Sequential(
    (conv): Conv2d(32, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (maxpool): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
  (layer2): Sequential(
    (conv): Conv2d(32, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (activation): Hardtanh(min_val=-1.0, max_val=1.0)
  )
  (layer3): Sequential(
    (conv): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (maxpool): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
  (layer4): Seq

In [11]:
pars.clf_lr = 0.0001
vis = visdom.Visdom(port=8097,env='clf_lr_0_0001')
train_unsupervised_ae(pars, vis=vis)

Setting up a new session...


save/CONV6/AE/
hardtanh_Cifar100_Adam_LR_0.0005_Epochs_100_CLF_Cifar10_Adam_LR_0.0001_Epochs_100_lam_20
Files already downloaded and verified
Files already downloaded and verified
Files already downloaded and verified
Files already downloaded and verified

Rep 1
Sequential(
  (layer0): Sequential(
    (conv): Conv2d(3, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (activation): Hardtanh(min_val=-1.0, max_val=1.0)
  )
  (layer1): Sequential(
    (conv): Conv2d(32, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (maxpool): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
  (layer2): Sequential(
    (conv): Conv2d(32, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (activation): Hardtanh(min_val=-1.0, max_val=1.0)
  )
  (layer3): Sequential(
    (conv): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (maxpool): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
  (layer4): Se

In [14]:
pars.clf_lr = 0.0002
vis = visdom.Visdom(port=8097,env='clf_lr_0_0002')
train_unsupervised_ae(pars, vis=vis)

Setting up a new session...


save/CONV6/AE/
hardtanh_Cifar100_Adam_LR_0.0005_Epochs_100_CLF_Cifar10_Adam_LR_0.0002_Epochs_100_lam_20
Files already downloaded and verified
Files already downloaded and verified
Files already downloaded and verified
Files already downloaded and verified

Rep 1
Sequential(
  (layer0): Sequential(
    (conv): Conv2d(3, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (activation): Hardtanh(min_val=-1.0, max_val=1.0)
  )
  (layer1): Sequential(
    (conv): Conv2d(32, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (maxpool): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
  (layer2): Sequential(
    (conv): Conv2d(32, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (activation): Hardtanh(min_val=-1.0, max_val=1.0)
  )
  (layer3): Sequential(
    (conv): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (maxpool): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
  (layer4): Se

In [12]:
pars.clf_lr = 0.0005
vis = visdom.Visdom(port=8097,env='clf_lr_0_0005')
train_unsupervised_ae(pars, vis=vis)

Setting up a new session...


save/CONV6/AE/
hardtanh_Cifar100_Adam_LR_0.0005_Epochs_100_CLF_Cifar10_Adam_LR_0.0005_Epochs_100_lam_20
Files already downloaded and verified
Files already downloaded and verified
Files already downloaded and verified
Files already downloaded and verified

Rep 1
Sequential(
  (layer0): Sequential(
    (conv): Conv2d(3, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (activation): Hardtanh(min_val=-1.0, max_val=1.0)
  )
  (layer1): Sequential(
    (conv): Conv2d(32, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (maxpool): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
  (layer2): Sequential(
    (conv): Conv2d(32, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (activation): Hardtanh(min_val=-1.0, max_val=1.0)
  )
  (layer3): Sequential(
    (conv): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (maxpool): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
  (layer4): Se

In [13]:
pars.clf_lr = 0.001
vis = visdom.Visdom(port=8097,env='clf_lr_0_001')
train_unsupervised_ae(pars, vis=vis)

Setting up a new session...


save/CONV6/AE/
hardtanh_Cifar100_Adam_LR_0.0005_Epochs_100_CLF_Cifar10_Adam_LR_0.001_Epochs_100_lam_20
Files already downloaded and verified
Files already downloaded and verified
Files already downloaded and verified
Files already downloaded and verified

Rep 1
Sequential(
  (layer0): Sequential(
    (conv): Conv2d(3, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (activation): Hardtanh(min_val=-1.0, max_val=1.0)
  )
  (layer1): Sequential(
    (conv): Conv2d(32, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (maxpool): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
  (layer2): Sequential(
    (conv): Conv2d(32, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (activation): Hardtanh(min_val=-1.0, max_val=1.0)
  )
  (layer3): Sequential(
    (conv): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (maxpool): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
  (layer4): Seq

In [33]:
sklearn_classifier = LogisticRegression(n_jobs=-1)
train_unsupervised_ae(pars,sklearn_classifier=sklearn_classifier)

save/CONV6/AE/
hardtanh_Cifar100_Adam_LR_0.0005_Epochs_100_CLF_Cifar10_Adam_LR_0.0005_Epochs_100_lam_20
Files already downloaded and verified
Files already downloaded and verified
Files already downloaded and verified
Files already downloaded and verified

Rep 1
Sequential(
  (layer0): Sequential(
    (conv): Conv2d(3, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (activation): Hardtanh(min_val=-1.0, max_val=1.0)
  )
  (layer1): Sequential(
    (conv): Conv2d(32, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (maxpool): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
  (layer2): Sequential(
    (conv): Conv2d(32, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (activation): Hardtanh(min_val=-1.0, max_val=1.0)
  )
  (layer3): Sequential(
    (conv): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (maxpool): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
  (layer4): Se

In [31]:
sklearn_classifier = SGDClassifier(n_jobs=-1, alpha=0.001)
train_unsupervised_ae(pars,sklearn_classifier=sklearn_classifier)

save/CONV6/AE/
hardtanh_Cifar100_Adam_LR_0.0005_Epochs_100_CLF_Cifar10_Adam_LR_0.0005_Epochs_100_lam_20
Files already downloaded and verified
Files already downloaded and verified
Files already downloaded and verified
Files already downloaded and verified

Rep 1
Sequential(
  (layer0): Sequential(
    (conv): Conv2d(3, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (activation): Hardtanh(min_val=-1.0, max_val=1.0)
  )
  (layer1): Sequential(
    (conv): Conv2d(32, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (maxpool): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
  (layer2): Sequential(
    (conv): Conv2d(32, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (activation): Hardtanh(min_val=-1.0, max_val=1.0)
  )
  (layer3): Sequential(
    (conv): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (maxpool): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
  (layer4): Se

In [30]:
sklearn_classifier = SGDClassifier(n_jobs=-1, alpha=0.005)
train_unsupervised_ae(pars,sklearn_classifier=sklearn_classifier)

save/CONV6/AE/
hardtanh_Cifar100_Adam_LR_0.0005_Epochs_100_CLF_Cifar10_Adam_LR_0.0005_Epochs_100_lam_20
Files already downloaded and verified
Files already downloaded and verified
Files already downloaded and verified
Files already downloaded and verified

Rep 1
Sequential(
  (layer0): Sequential(
    (conv): Conv2d(3, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (activation): Hardtanh(min_val=-1.0, max_val=1.0)
  )
  (layer1): Sequential(
    (conv): Conv2d(32, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (maxpool): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
  (layer2): Sequential(
    (conv): Conv2d(32, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (activation): Hardtanh(min_val=-1.0, max_val=1.0)
  )
  (layer3): Sequential(
    (conv): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (maxpool): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
  (layer4): Se

In [28]:
sklearn_classifier = SGDClassifier(n_jobs=-1, alpha=0.01)
train_unsupervised_ae(pars,sklearn_classifier=sklearn_classifier)

save/CONV6/AE/
hardtanh_Cifar100_Adam_LR_0.0005_Epochs_100_CLF_Cifar10_Adam_LR_0.0005_Epochs_100_lam_20
Files already downloaded and verified
Files already downloaded and verified
Files already downloaded and verified
Files already downloaded and verified

Rep 1
Sequential(
  (layer0): Sequential(
    (conv): Conv2d(3, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (activation): Hardtanh(min_val=-1.0, max_val=1.0)
  )
  (layer1): Sequential(
    (conv): Conv2d(32, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (maxpool): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
  (layer2): Sequential(
    (conv): Conv2d(32, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (activation): Hardtanh(min_val=-1.0, max_val=1.0)
  )
  (layer3): Sequential(
    (conv): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (maxpool): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
  (layer4): Se

In [25]:
sklearn_classifier = SGDClassifier(n_jobs=-1, alpha=0.02)
train_unsupervised_ae(pars,sklearn_classifier=sklearn_classifier)

save/CONV6/AE/
hardtanh_Cifar100_Adam_LR_0.0005_Epochs_100_CLF_Cifar10_Adam_LR_0.0005_Epochs_100_lam_20
Files already downloaded and verified
Files already downloaded and verified
Files already downloaded and verified
Files already downloaded and verified

Rep 1
Sequential(
  (layer0): Sequential(
    (conv): Conv2d(3, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (activation): Hardtanh(min_val=-1.0, max_val=1.0)
  )
  (layer1): Sequential(
    (conv): Conv2d(32, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (maxpool): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
  (layer2): Sequential(
    (conv): Conv2d(32, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (activation): Hardtanh(min_val=-1.0, max_val=1.0)
  )
  (layer3): Sequential(
    (conv): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (maxpool): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
  (layer4): Se

In [29]:
sklearn_classifier = SGDClassifier(n_jobs=-1, alpha=0.05)
train_unsupervised_ae(pars,sklearn_classifier=sklearn_classifier)

save/CONV6/AE/
hardtanh_Cifar100_Adam_LR_0.0005_Epochs_100_CLF_Cifar10_Adam_LR_0.0005_Epochs_100_lam_20
Files already downloaded and verified
Files already downloaded and verified
Files already downloaded and verified
Files already downloaded and verified

Rep 1
Sequential(
  (layer0): Sequential(
    (conv): Conv2d(3, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (activation): Hardtanh(min_val=-1.0, max_val=1.0)
  )
  (layer1): Sequential(
    (conv): Conv2d(32, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (maxpool): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
  (layer2): Sequential(
    (conv): Conv2d(32, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (activation): Hardtanh(min_val=-1.0, max_val=1.0)
  )
  (layer3): Sequential(
    (conv): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (maxpool): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
  (layer4): Se

In [27]:
sklearn_classifier = SGDClassifier(n_jobs=-1, alpha=0.1)
train_unsupervised_ae(pars,sklearn_classifier=sklearn_classifier)

save/CONV6/AE/
hardtanh_Cifar100_Adam_LR_0.0005_Epochs_100_CLF_Cifar10_Adam_LR_0.0005_Epochs_100_lam_20
Files already downloaded and verified
Files already downloaded and verified
Files already downloaded and verified
Files already downloaded and verified

Rep 1
Sequential(
  (layer0): Sequential(
    (conv): Conv2d(3, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (activation): Hardtanh(min_val=-1.0, max_val=1.0)
  )
  (layer1): Sequential(
    (conv): Conv2d(32, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (maxpool): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
  (layer2): Sequential(
    (conv): Conv2d(32, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (activation): Hardtanh(min_val=-1.0, max_val=1.0)
  )
  (layer3): Sequential(
    (conv): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (maxpool): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
  (layer4): Se

In [32]:
sklearn_classifier = SGDClassifier(n_jobs=-1, alpha=0.5)
train_unsupervised_ae(pars,sklearn_classifier=sklearn_classifier)

save/CONV6/AE/
hardtanh_Cifar100_Adam_LR_0.0005_Epochs_100_CLF_Cifar10_Adam_LR_0.0005_Epochs_100_lam_20
Files already downloaded and verified
Files already downloaded and verified
Files already downloaded and verified
Files already downloaded and verified

Rep 1
Sequential(
  (layer0): Sequential(
    (conv): Conv2d(3, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (activation): Hardtanh(min_val=-1.0, max_val=1.0)
  )
  (layer1): Sequential(
    (conv): Conv2d(32, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (maxpool): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
  (layer2): Sequential(
    (conv): Conv2d(32, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (activation): Hardtanh(min_val=-1.0, max_val=1.0)
  )
  (layer3): Sequential(
    (conv): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (maxpool): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
  (layer4): Se

In [ ]:
vis = visdom.Visdom(port=8097,env='lam_20_sklearn')
sklearn_classifier = SGDClassifier(verbose=0, n_jobs=-1)
train_unsupervised_ae(pars,vis=vis, sklearn_classifier=sklearn_classifier)

Setting up a new session...


save/CONV6/AE/
hardtanh_Cifar100_Adam_LR_0.0005_Epochs_100_CLF_Cifar10_Adam_LR_0.0005_Epochs_100_lam_20
Files already downloaded and verified
Files already downloaded and verified
Files already downloaded and verified
Files already downloaded and verified

Rep 1
Sequential(
  (layer0): Sequential(
    (conv): Conv2d(3, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (activation): Hardtanh(min_val=-1.0, max_val=1.0)
  )
  (layer1): Sequential(
    (conv): Conv2d(32, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (maxpool): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
  (layer2): Sequential(
    (conv): Conv2d(32, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (activation): Hardtanh(min_val=-1.0, max_val=1.0)
  )
  (layer3): Sequential(
    (conv): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (maxpool): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
  (layer4): Se

In [8]:
pars = PARS(device, datapath, savepath)
pars.architecture = 'CONV6'
pars.LR = 5e-4
pars.clf_lr = 5e-4
pars.epochs = 100
pars.clf_epochs = 100
pars.nonlinear = 'hardtanh'
pars.repeat = 1
pars.lam = 50
print(pars)

architecture: CONV6
nonlinear: hardtanh
batch_size: 500
headsize: 64
dataset: Cifar100
loss: SimCLR
OPT: Adam
LR: 0.0005
epochs: 100
clf_dataset: Cifar10
clf_loss: CE
clf_opt: Adam
clf_lr: 0.0005
clf_epochs: 100
repeat: 1
device: cuda:0
datapath: data/
savepath: save/
loadnet: None
loadclf: None
lam: 50
auxnonlinear: None



In [9]:
vis = visdom.Visdom(port=8097,env='lam_50_sklearn')
sklearn_classifier = SGDClassifier(verbose=0, n_jobs=-1)
train_unsupervised_ae(pars,vis=vis, sklearn_classifier=sklearn_classifier)

Setting up a new session...


save/CONV6/AE/
hardtanh_Cifar100_Adam_LR_0.0005_Epochs_100_CLF_Cifar10_Adam_LR_0.0005_Epochs_100_lam_50
Files already downloaded and verified
Files already downloaded and verified
Files already downloaded and verified
Files already downloaded and verified

Rep 1
Sequential(
  (layer0): Sequential(
    (conv): Conv2d(3, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (activation): Hardtanh(min_val=-1.0, max_val=1.0)
  )
  (layer1): Sequential(
    (conv): Conv2d(32, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (maxpool): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
  (layer2): Sequential(
    (conv): Conv2d(32, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (activation): Hardtanh(min_val=-1.0, max_val=1.0)
  )
  (layer3): Sequential(
    (conv): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (maxpool): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
  (layer4): Se

In [19]:
pars = PARS(device, datapath, savepath)
pars.architecture = 'CONV6'
pars.LR = 5e-4
pars.clf_lr = 5e-4
pars.epochs = 100
pars.clf_epochs = 100
pars.nonlinear = 'hardtanh'
pars.repeat = 1
pars.lam = 100
print(pars)

architecture: CONV6
nonlinear: hardtanh
batch_size: 500
headsize: 64
dataset: Cifar100
loss: SimCLR
OPT: Adam
LR: 0.0005
epochs: 100
clf_dataset: Cifar10
clf_loss: CE
clf_opt: Adam
clf_lr: 0.0005
clf_epochs: 100
repeat: 1
device: cuda:0
datapath: data/
savepath: save/
loadnet: None
loadclf: None
lam: 100
auxnonlinear: None



In [10]:
vis = visdom.Visdom(port=8097,env='lam_100_sklearn')
sklearn_classifier = SGDClassifier(verbose=0, n_jobs=-1)
train_unsupervised_ae(pars,vis=vis, sklearn_classifier=sklearn_classifier)

Setting up a new session...


save/CONV6/AE/
hardtanh_Cifar100_Adam_LR_0.0005_Epochs_100_CLF_Cifar10_Adam_LR_0.0005_Epochs_100_lam_50
Files already downloaded and verified
Files already downloaded and verified
Files already downloaded and verified
Files already downloaded and verified

Rep 1
Sequential(
  (layer0): Sequential(
    (conv): Conv2d(3, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (activation): Hardtanh(min_val=-1.0, max_val=1.0)
  )
  (layer1): Sequential(
    (conv): Conv2d(32, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (maxpool): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
  (layer2): Sequential(
    (conv): Conv2d(32, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (activation): Hardtanh(min_val=-1.0, max_val=1.0)
  )
  (layer3): Sequential(
    (conv): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (maxpool): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
  (layer4): Se

KeyboardInterrupt: 

In [ ]:
pars = PARS(device, datapath, savepath)
pars.architecture = 'CONV6'
pars.LR = 5e-4
pars.clf_lr = 5e-4
pars.epochs = 100
pars.clf_epochs = 100
pars.nonlinear = 'hardtanh'
pars.repeat = 1
pars.lam = 500
print(pars)

architecture: CONV6
nonlinear: hardtanh
batch_size: 500
headsize: 64
dataset: Cifar100
loss: SimCLR
OPT: Adam
LR: 0.0005
epochs: 300
clf_dataset: Cifar10
clf_loss: CE
clf_opt: Adam
clf_lr: 0.0005
clf_epochs: 100
repeat: 1
device: cuda:0
datapath: data/
savepath: save/
loadnet: None
loadclf: None
lam: 0.95
auxnonlinear: None



In [ ]:
vis = visdom.Visdom(port=8097,env='lam_500_sklearn')
sklearn_classifier = SGDClassifier(verbose=0, n_jobs=-1)
train_unsupervised_ae(pars,vis=vis, sklearn_classifier=sklearn_classifier)

Setting up a new session...


save/CONV6/AE/
hardtanh_Cifar100_Adam_LR_0.0005_Epochs_300_CLF_Cifar10_Adam_LR_0.0005_Epochs_100_lam_0.95
Files already downloaded and verified
Files already downloaded and verified
Files already downloaded and verified
Files already downloaded and verified

Rep 1
Sequential(
  (layer0): Sequential(
    (conv): Conv2d(3, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (activation): Hardtanh(min_val=-1.0, max_val=1.0)
  )
  (layer1): Sequential(
    (conv): Conv2d(32, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (maxpool): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
  (layer2): Sequential(
    (conv): Conv2d(32, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (activation): Hardtanh(min_val=-1.0, max_val=1.0)
  )
  (layer3): Sequential(
    (conv): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (maxpool): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
  (layer4): 

Epoch 52, loss = 0.0219, time: 20.1205
reconstruction loss = 0.0098, similarity loss: 0.2530
Epoch 53, loss = 0.0241, time: 27.6657
reconstruction loss = 0.0108, similarity loss: 0.2755
Epoch 54, loss = 0.0230, time: 30.1208
reconstruction loss = 0.0094, similarity loss: 0.2814
Epoch 55, loss = 0.0235, time: 28.3908
reconstruction loss = 0.0094, similarity loss: 0.2908
Epoch 56, loss = 0.0213, time: 29.3284
reconstruction loss = 0.0088, similarity loss: 0.2598
Epoch 57, loss = 0.0222, time: 30.7263
reconstruction loss = 0.0094, similarity loss: 0.2657
Epoch 58, loss = 0.0242, time: 29.3793
reconstruction loss = 0.0100, similarity loss: 0.2938
Epoch 59, loss = 0.0266, time: 28.3193
reconstruction loss = 0.0126, similarity loss: 0.2928
Epoch 60, loss = 0.0218, time: 27.9703
reconstruction loss = 0.0085, similarity loss: 0.2747
Epoch 61, loss = 0.0238, time: 25.6389
reconstruction loss = 0.0102, similarity loss: 0.2834
Epoch 62, loss = 0.0250, time: 24.8097
reconstruction loss = 0.0096, s

Epoch 140, loss = 0.0222, time: 31.6562
reconstruction loss = 0.0082, similarity loss: 0.2882
Epoch 141, loss = 0.0184, time: 27.7980
reconstruction loss = 0.0070, similarity loss: 0.2355
Epoch 142, loss = 0.0206, time: 30.2612
reconstruction loss = 0.0068, similarity loss: 0.2830
Epoch 143, loss = 0.0184, time: 24.5558
reconstruction loss = 0.0065, similarity loss: 0.2453
Epoch 144, loss = 0.0193, time: 30.7128
reconstruction loss = 0.0068, similarity loss: 0.2579
Epoch 145, loss = 0.0190, time: 31.2786
reconstruction loss = 0.0068, similarity loss: 0.2522
Epoch 146, loss = 0.0203, time: 27.6539
reconstruction loss = 0.0069, similarity loss: 0.2746
Epoch 147, loss = 0.0195, time: 31.2839
reconstruction loss = 0.0071, similarity loss: 0.2553
Epoch 148, loss = 0.0195, time: 29.9488
reconstruction loss = 0.0072, similarity loss: 0.2525
Epoch 149, loss = 0.0193, time: 24.8118
reconstruction loss = 0.0069, similarity loss: 0.2552
Epoch 150, loss = 0.0201, time: 21.3542
reconstruction loss 

Epoch 228, loss = 0.0173, time: 25.3660
reconstruction loss = 0.0057, similarity loss: 0.2378
Epoch 229, loss = 0.0167, time: 25.1947
reconstruction loss = 0.0058, similarity loss: 0.2250
Epoch 230, loss = 0.0198, time: 23.5214
reconstruction loss = 0.0061, similarity loss: 0.2820
Epoch 231, loss = 0.0195, time: 19.9417
reconstruction loss = 0.0062, similarity loss: 0.2722
Epoch 232, loss = 0.0193, time: 19.8857
reconstruction loss = 0.0075, similarity loss: 0.2435
Epoch 233, loss = 0.0177, time: 24.0190
reconstruction loss = 0.0057, similarity loss: 0.2458
Epoch 234, loss = 0.0184, time: 24.4978
reconstruction loss = 0.0065, similarity loss: 0.2457
Epoch 235, loss = 0.0199, time: 20.9471
reconstruction loss = 0.0062, similarity loss: 0.2808
Epoch 236, loss = 0.0197, time: 20.7490
reconstruction loss = 0.0066, similarity loss: 0.2692
Epoch 237, loss = 0.0192, time: 20.8075
reconstruction loss = 0.0069, similarity loss: 0.2526
Epoch 238, loss = 0.0182, time: 20.8566
reconstruction loss 

Epoch 0, loss = 1.5091, val.acc = 0.5900
Epoch 1, loss = 1.1561, val.acc = 0.6230
Epoch 2, loss = 1.0570, val.acc = 0.6394
Epoch 3, loss = 0.9917, val.acc = 0.6480
Epoch 4, loss = 0.9422, val.acc = 0.6540
Epoch 5, loss = 0.9016, val.acc = 0.6598
Epoch 6, loss = 0.8669, val.acc = 0.6614
Epoch 7, loss = 0.8366, val.acc = 0.6622
Epoch 8, loss = 0.8097, val.acc = 0.6670
Epoch 9, loss = 0.7856, val.acc = 0.6662
Epoch 10, loss = 0.7636, val.acc = 0.6656
Epoch 11, loss = 0.7435, val.acc = 0.6640
Epoch 12, loss = 0.7249, val.acc = 0.6624
Epoch 13, loss = 0.7077, val.acc = 0.6632
Epoch 14, loss = 0.6916, val.acc = 0.6626
Epoch 15, loss = 0.6766, val.acc = 0.6620
Epoch 16, loss = 0.6624, val.acc = 0.6614
Epoch 17, loss = 0.6489, val.acc = 0.6604
Epoch 18, loss = 0.6362, val.acc = 0.6602
Epoch 19, loss = 0.6241, val.acc = 0.6602
Epoch 20, loss = 0.6125, val.acc = 0.6602
Epoch 21, loss = 0.6015, val.acc = 0.6582
Epoch 22, loss = 0.5909, val.acc = 0.6590
Epoch 23, loss = 0.5808, val.acc = 0.6594
Ep

- average reconstruction loss
- reconstruction result
- zero weight on BT
- lambda from small to large

- take the square root
- change lambda
- change the classifier

In [ ]:
pars = PARS(device, datapath, savepath)
pars.architecture = 'CONV6'
pars.LR = 0.0001
pars.clf_lr = 0.001
pars.epochs = 300
pars.clf_epochs = 100
pars.nonlinear = 'hardtanh'
pars.repeat = 1
pars.loss = "BarlowTwins"
pars.lam = 0.5
print(pars)

In [ ]:
criterion = BarlowTwinsLoss(pars.batch_size, pars.lam, pars.device)
train_unsupervised(pars, criterion=criterion)